
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: movierating_app_development


test:
  <<: *default
  database: movierating_app_test

production:
  <<: *default
  database: movierating_app_production
  username: movierating_app
  password: <%= ENV['MOVIERATING_APP_DATABASE_PASSWORD'] %>
